### ISSUE TITLE
Cross-Class Skills - Burst of Flames (XP+Damage) - Error computing damage

### ISSUE THREAD

**Issue by Futeko** [mike-the-monk/Habitica-customizations#4]
Hi!

I've been using the Cross-Class Skill "Burst of Flames" (XP+Damage version) without issues for a while, but today I got the error "Error computing damage. Please contact the author of the script to debug (note to author: final iteration triggered this message)." when using the skill.

Since I did not encounter the issue before, my guess is that it has to do with a specific combination of values.
If I'm not mistaken, the previous day I was able to use the skill without any issues, and I had 179.5 INT
Today I used the skill and got the error, with 180.5 INT

My understanding is that the change in INT changed the target damage of the skill = ceil(INT/10) -> was 18 before, is now 19
(I don't think the task value has any impact on the damage here, but just in case, it would have been about 15.62)

Looking at the function returning the error (setpointIteration), my guess is that this new value led the function into a situation where:
* targetDamage > damageLow
* targetDamage > damageMidpoint
* targetDamage **= damageHigh**

which caused the issue, as the conditions check the following:
* if (damageLow >= targetDamage) then LOW
* else if (damageMidPoint >= targetDamage) then MID
* else if (damageHigh **> targetDamage**) then HIGH
* else ERROR

So I believe ERROR happened here because damageHigh = targetDamage, which eluded all the cases.

And so to prevent the issue from happening, we'd need to change
* let targetBelowHigh = (damageHigh **> targetDamage**) ? true : false
to
* let targetBelowHigh = (damageHigh **>= targetDamage**) ? true : false

I made that change on my deployment of the script, and tried to use it again (with now 181.5 INT but which still gives a targetDamage of 19) and it went fine - so I believe that was indeed the issue.

**Comment by mike-the-monk** [comment]
So that's what was causing it! Someone else had the same issue but I had no idea why, and it resolved on its own (probably because their stats changed).

Thanks for testing your proposed solution and confirming that it works. If you want, you could open it as a pull request and I can merge your solution into the existing code, or, I could always just make the change myself. Up to you.
------- Original Message -------

**Comment by Futeko** [comment]
Haha, cool! My pleasure :)

I went the pull request route to try that feature out (I had never used it before), so hopefully I did everything correctly :'D
