### ISSUE TITLE
Anti-Potions Script shows error

### ISSUE THREAD

**Issue by Wizards-god** [mike-the-monk/Habitica-customizations#9]
Hey,

I tried Installing your extension(Anti-Potions) by following all the steps on the Habitica Wiki, but in the end, when I ran the doOneTimeSetup function, it gives me an error.
![image](https://github.com/mike-the-monk/Habitica-customizations/assets/70703332/6000e7e1-ff62-47ac-a10a-b3c7a11684d8)
Is there any particular reason why this is happening?
Moreover, How do I solve it?

Thanks

**Comment by mike-the-monk** [comment]
That's new, I haven't seen that happen before. It means something broke and I'll have to troubleshoot it this weekend.

In the meantime, you could try installing my superscript instead (it contains all my scripts), you'd simply select the three anti-potions as the ones to create. It's still possible you run into the same issue, but it's possible there's a version difference between Anti-Potions and superscript that I haven't caught yet.

------- Original Message -------

**Comment by Wizards-god** [comment]
Thx for helping me out, It works with the Superscript

**Comment by mike-the-monk** [comment]
Great to know! I found and fixed the issue in Anti-Potions, it was slightly different from Superscript.

**Comment by mike-the-monk** [comment]
Great to know! I found and fixed the issue in Anti-Potions, it was slightly different from Superscript.

**Comment by Wizards-god** [comment]
Thanks man, appreciate the effort
